#
//  ios-ci.yml
//  NoteKeeper
//
//  Created by Macbook Air on 03.06.2025.
//
name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2' 

    - name: Build iOS project
      run: |
        xcodebuild clean build \
        -scheme NoteKeeper \
        -destination 'platform=iOS Simulator,name=iPhone 14' \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

